### DISCUSSION TITLE
Default Values

### DISCUSSION THREAD

**Discussion by StevenMilneDev** [StevenMilneDev/badger#17] [Show and tell]
When Badger can't find a variable referenced in a badge it skips creating it. This can be a pain if you want a variable to be optional with a default value. Environment variables can be used to provide default values for your variables. This thread will show you how.

In this example, we will be creating an optional [Trello](https://trello.com/) badge. It will use a dynamic variable to get the Trello card URL out of the PR description. If the URL isn't provided then the badge will be skipped. A second dynamic variable will be used to get a human readable name for the card. If the name isn't provided then a sensible default will be used.

## Badge Configuration
To add this Trello badge, we'll use the following config in the workflow file;

```yml
- name: Add Badges
  id: badger
  uses: StevenMilneDev/badger@1.0.3
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    badge-01: 'Trello: {{trello.card}} (link={{trello.url}})(logo=trello)
```

This will give us a single badge with two required fields. But we want the `{{trello.card}}` field to be optional. To do this we must add an environment variable with the name `TRELLO_CARD` and give it the default value. Below is a full example;

```yml
- name: Add Badges
  id: badger
  uses: StevenMilneDev/badger@1.0.3
  env:
    TRELLO_CARD: Untitled Card
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    badge-01: 'Trello: {{trello.card}} (link={{trello.url}})(logo=trello)
```

Now when `trello.card` can't be found in the PR description, then it will get the default value of "Untitled Card".

## PR Template
Now we can add the two fields to the PR template for the PR creator to fill in;

```
---
## 🦡 Badger

Trello Card: 
Trello URL: 
---

Write your PR description here...
```

Creating a test PR with this configuration and template should now satisfy the behaviour we were looking to achieve.
