### ISSUE TITLE
Badger Deletes PR Description when Rerun

### ISSUE THREAD

**Issue by StevenMilne-Sonocent** [StevenMilneDev/badger#18]
This appears to be a bug where re-running the GitHub action will cause it to silently fail and delete the entire PR description. Below is the logs from such a failed run;

```
Generating badges...
Warning: Could not find 🦡 Badger section in description
Warning: Skipping badge-01: Could not resolve variable {{SAFE_BRANCH_NAME}}
Warning: Could not find 🦡 Badger section in description
Warning: Skipping badge-02: Could not resolve variable {{SAFE_BRANCH_NAME}}
Warning: Could not find 🦡 Badger section in description
Warning: Skipping badge-03: Could not resolve variable {{JENKINS_DASHBOARD}}
Warning: Could not find 🦡 Badger section in description
Warning: Skipping badge-04: Could not resolve variable {{trello.card}}
Warning: Could not find 🦡 Badger section in description
Warning: Skipping badge-05: Could not resolve variable {{jira.card}}
Updating PR description...
```

In this case it also wasn't able to resolve any of the environment variables from the run configuration;

```yml
name: Badger
on:
  pull_request:
    types: [opened]

jobs:
  pr-description:
    runs-on: ubuntu-latest
    name: Update PR Description
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Safe Branch Name
        id: branch_name
        run: |
          source infrastructure/scripts/util/safe-branch-name.sh
          SAFE_BRANCH_NAME=$(getSafeBranchName "$GITHUB_HEAD_REF")
          echo "::set-output name=SAFE_BRANCH_NAME::$SAFE_BRANCH_NAME"
      - name: Add Badges
        id: badger
        uses: StevenMilneDev/badger@v1.0.3
        env:
          TRELLO_CARD: Untitled Card
          JIRA_CARD: Untitled Card
          JENKINS_DASHBOARD: 'https://jenkins.example.com/blue/organizations/jenkins/glean/activity'
          GLEAN_BRANDING: '(logoColor=white)(labelColor=5f5ffc)(color=3d3d66)'
          SAFE_BRANCH_NAME: ${{ steps.branch_name.outputs.SAFE_BRANCH_NAME }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          badge-01: 'Glean Web: app.{{SAFE_BRANCH_NAME}}.example.com (link=https://app.{{SAFE_BRANCH_NAME}}.example.com)(logo=googleChrome){{GLEAN_BRANDING}}'
          badge-02: 'Glean Admin: admin.{{SAFE_BRANCH_NAME}}.example.com (link=https://admin.{{SAFE_BRANCH_NAME}}.example.com)(logo=googleChrome){{GLEAN_BRANDING}}'
          badge-03: 'Jenkins: All Branch Builds (link={{JENKINS_DASHBOARD}}?branch={{branch}})(logo=jenkins)(logoColor=white)(labelColor=d24939)(color=414150)'
          badge-04: 'Trello: {{trello.card}} (link={{trello.url}})(logo=trello)(logoColor=white)(labelColor=0065ff)(color=e3e3e7)'
          badge-05: 'Jira: {{jira.card}} (link={{jira.url}})(logo=jira)(logoColor=white)(labelColor=0052CC)(color=414150)'
```
